kind: ConfigMap 
apiVersion: v1
metadata:
  name: dev-configmap-{{ .Values.configmap.version }}
data:
  BG_COLOR: '#12181b'
  FONT_COLOR: '#FFFFFF'
  CUSTOM_HEADER: {{ .Values.configmap.data.CUSTOM_HEADER }}
